#!/bin/bash

# Check if an argument has been provided
if [ $# -eq 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Retrieve the IP address from the first argument
ip_address=$1

# Ping the IP address 5 times
ping -c 5 $ip_address

# Check the exit status of the ping command
if [ $? -eq 0 ]; then
  echo "$ip_address is reachable."
else
  echo "$ip_address is unreachable."
fi
